### ISSUE TITLE
Android 12+ error of "apt: inaccessible or not found". How to resolve?

### ISSUE THREAD

**Issue by jeysonlr** [awnto/rinix#12]
Android 12+ error of "apt: inaccessible or not found". How to resolve? 

apt or any other command

**Comment by awnto** [comment]
can you send screenshot

**Comment by jeysonlr** [comment]
![image](https://github.com/awnto/rinix/assets/46712375/2c46d097-8d6d-4a9d-8b4e-fc2cafd55b32)

**Comment by awnto** [comment]
install rnx core app also

for help
https://youtu.be/ucSFl0Cz550

**Comment by Tryingjusttolive20242** [comment]
Same here
