### ISSUE TITLE
Package "udisks2" didn't install correctly, solved

### ISSUE THREAD

**Issue by davidpiano** [awnto/rinix#2]
I found a report of the same problem on the Termux issues page, with a working solution [here](https://github.com/termux/termux-app/issues/1456).

**Comment by awnto** [comment]
thanks 

but this is not a solution

this will hold 'udisks2' package


better to ignore this error

we may fix this error in next version of RNX

join us on telegram to stay updated with RNX
[telegram links are given at bottom at RNX Docs]
