### ISSUE TITLE
/system/bin/sh: termux-setup-termux-storage: inaccessible or not found 127|:/data/data/com.awnto.rnx.rtmx/files/home $

### ISSUE THREAD

**Issue by rockysking46** [awnto/rinix#4]
Fix it

**Comment by awnto** [comment]
Note : 
for android 10 or higher
install rnx core , rnx neo apk from website 
https://rinix.awnto.com/docs/
not from playstore 
then restart phone

**Comment by Anjalobinoy** [comment]
Tool  sheyar
