### ISSUE TITLE
RNX xio 

### ISSUE THREAD

**Issue by Reallucky12** [awnto/rinix#5]
I can't log in into RNX xio and termux

**Comment by awnto** [comment]
can you send screenshot

**Comment by NZ-247** [comment]
![Screenshot_20231026-092214](https://github.com/awnto/rinix/assets/134312875/d2019288-a259-48b4-883d-f722ec756871)

I have this problem, can you help me please

**Comment by awnto** [comment]
install RNX Core app also

for help
https://youtu.be/ucSFl0Cz550

**Comment by NZ-247** [comment]
![Screenshot_20231026-100025](https://github.com/awnto/rinix/assets/134312875/120d2cb8-3d89-46e9-b143-4803157afc3c)

now it just looks like this, when I opened it for the first time it didn't do any downloading like in the tutorial...

**Comment by Manikandan17S** [comment]
![Uploading Screenshot_2023-11-22-08-56-45-454_com.awnto.rnx.neo.jpg…]()
I have this problem? What I do

**Comment by awnto** [comment]
watch the full video
need command to install linux

rnx get-default-linux
